### ISSUE TITLE
weak is listed as a dependency & optionalDependency

### ISSUE THREAD

**Issue by jonstorer** [substack/dnode#170]
one or the other please

**Comment by donaldpipowitch** [comment]
@substack When I call `$ npm i dnode` in an empty directory I get a `package.json` which lists `weak` inside `dependencies` and `optionalDependencies` (on Mac). When installing `dnode` on Linux with Node 4.1 and npm 3.3.3 the installation for `weak` fails. If my script starts I get 

````
Error: Cannot find module 'weak'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at new D (/var/lib/jenkins/workspace/foo/node_modules/dnode/index.js:28:20)
````

Is this an optional dependency or not?
