### ISSUE TITLE
node 4.1.2 (npm v2.14.4)   Error: Module version mismatch. Expected 46, got 14.

### ISSUE THREAD

**Issue by chelsh** [substack/dnode#175]
Error: Module version mismatch. Expected 46, got 14.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function._load (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/var/www/Server-Push/source/node_modules/dnode/node_modules/weak/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/var/www/Server-Push/source/node_modules/dnode/node_modules/weak/lib/weak.js:7:35)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)

**Comment by apsavin** [comment]
@chelsh can you give exact steps to reproduce?
