### ISSUE TITLE
Transmission parameters error：TypeError: undefined is not a function

### ISSUE THREAD

**Issue by chelsh** [substack/dnode#177]
client:
```
                               var params = {};
                                params.user = req.user;
                                params.topic = topic;
                                params.lon = lon;
                                params.lat = lat;
                                params.isSpread = true;
                                params.grade = grade;
                                remote.spreadTopic(params,function(err,result){

                                });
```
server:
```
var server = dnode({
    spreadTopic : function(params,cb){
        var user = params.user;
        var topic = params.topic;
        var lon = params.lon;
        var lat = params.lat;
        var isSpread = params.isSpread;
        var grade = params.grade;

```

run code, and client happen error:

```
Thu, 15 Oct 2015 04:19:53 GMT uncaughtException undefined is not a function
TypeError: undefined is not a function
    at String.Document.get (/Users/whw/code/Server-API2/node_modules/mongoose/lib/document.js:706:21)
    at model.Object.defineProperty.get [as _id] (/Users/whw/code/Server-API2/node_modules/mongoose/lib/document.js:1234:45)
    at model.idGetter (/Users/whw/code/Server-API2/node_modules/mongoose/lib/schema.js:97:37)
    at VirtualType.applyGetters (/Users/whw/code/Server-API2/node_modules/mongoose/lib/virtualtype.js:77:25)
    at model.Document.get (/Users/whw/code/Server-API2/node_modules/mongoose/lib/document.js:717:18)
    at applyGetters (/Users/whw/code/Server-API2/node_modules/mongoose/lib/document.js:1622:35)
    at model.Document.toObject (/Users/whw/code/Server-API2/node_modules/mongoose/lib/document.js:1523:5)
    at model.Document.toJSON (/Users/whw/code/Server-API2/node_modules/mongoose/lib/document.js:1662:15)
    at Object.stringify (native)
    at Proto.<anonymous> (/Users/whw/code/Server-API2/node_modules/dnode/lib/dnode.js:62:37)

```

**Comment by chelsh** [comment]
any help？

**Comment by chelsh** [comment]
any help？
