### ISSUE TITLE
Crash with uncaught exception Error: write ECONNRESET

### ISSUE THREAD

**Issue by Lellansin** [substack/dnode#178]
This is the error which cause server crashed.

    stream.js:94
          throw er; // Unhandled stream error in pipe.
                ^
    Error: write ECONNRESET
        at errnoException (net.js:904:11)
        at Object.afterWrite (net.js:720:19)

And this code can't catch the exception
```javascript
process.on('uncaughtException', function(err) {
    console.error(' Caught exception: ', err.stack, err);
});
````

This code shows the error should be caught, but it didn't.
```javascript
var server = dnode(connector);

server.listen(config.connector.port);

server.emit('error', new Error('some connection error'));

process.on('uncaughtException', function(err) {
    console.error(' Caught exception: ', err.stack, err);
});
```

My node is v0.10.26, dnode v1.2.2, and I wonder if this is a problem with version, or I can fix it with some dnode API.

Thanks for reply.

**Comment by jfosnight** [comment]
I know that this is a super old question, but I just ran across the same issue.  After digging into it, it looks like there was a small error in the `index.js` file.

On line 106 of `index.js` the `d.emit('error', err);` needs to be changed to `server.emit('error', err);`

Example usage:
```javascript
var d = dnode(connector);
var server = d.listen(port);

// Register event listener
server.on('error', function(error){
  // handle error.
});
```
