### ISSUE TITLE
Error: Can't find Python executable "python"

### ISSUE THREAD

**Issue by Binom777** [substack/dnode#181]
I do not understand.
To install I need a python?

> C:\Users\Binom\GoogleDrv\Projects\nodejs\MusicBox>npm install dnode
> 
> > weak@1.0.1 install C:\Users\Binom\GoogleDrv\Projects\nodejs\MusicBox\node_modules\weak
> > node-gyp rebuild
> 
> 
> C:\Users\Binom\GoogleDrv\Projects\nodejs\MusicBox\node_modules\weak>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
> gyp ERR! configure error
> gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
> gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:401:14)
> gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:356:11
> gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
> gyp ERR! System Windows_NT 6.1.7601
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> gyp ERR! cwd C:\Users\Binom\GoogleDrv\Projects\nodejs\MusicBox\node_modules\weak
> gyp ERR! node -v v5.7.1
> gyp ERR! node-gyp -v v3.2.1
> gyp ERR! not ok
> npm WARN install:weak@1.0.1 weak@1.0.1 install: `node-gyp rebuild`
> npm WARN install:weak@1.0.1 Exit status 1
> nodejs@1.0.0 C:\Users\Binom\GoogleDrv\Projects\nodejs\MusicBox
> +-- dnode@1.2.2  extraneous
> +-- domready@1.0.8  extraneous
> +-- ecstatic@1.4.0  extraneous
> +-- ejs@2.4.1  extraneous
> +-- glob@7.0.3  extraneous
> +-- requestify@0.1.17
> +-- shoe@0.0.15  extraneous
> +-- socket.io@1.4.5  extraneous
> +-- soundmanager2@2.97.20150601-a  extraneous
> `-- vk-api@0.1.0

**Comment by Binom777** [comment]
After installing python

> 
> C:\Users\Binom\GoogleDrv\Projects\nodejs\MusicBox>npm install dnode shoe domready ecstatic
> 
> > weak@1.0.1 install C:\Users\Binom\GoogleDrv\Projects\nodejs\MusicBox\node_modules\weak
> > node-gyp rebuild
> 
> 
> C:\Users\Binom\GoogleDrv\Projects\nodejs\MusicBox\node_modules\weak>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
> Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
> MSBUILD : error MSB3428: Загрузка компонента Visual C++ "VCBuild.exe" невозможна. Способы решения проблемы: 1) установка .NET Framework 2.0 SDK, 2) установка Microsoft Visual Studio 2005 или 3) указание адреса компонента в системном пути, если компонент у
> становлен в другом месте.  [C:\Users\Binom\GoogleDrv\Projects\nodejs\MusicBox\node_modules\weak\build\binding.sln]
> gyp ERR! build error
> gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
> gyp ERR! stack     at emitTwo (events.js:100:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
> gyp ERR! System Windows_NT 6.1.7601
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> gyp ERR! cwd C:\Users\Binom\GoogleDrv\Projects\nodejs\MusicBox\node_modules\weak
> gyp ERR! node -v v5.7.1
> gyp ERR! node-gyp -v v3.2.1
> gyp ERR! not ok
> npm WARN install:weak@1.0.1 weak@1.0.1 install: `node-gyp rebuild`
> npm WARN install:weak@1.0.1 Exit status 1
> nodejs@1.0.0 C:\Users\Binom\GoogleDrv\Projects\nodejs\MusicBox
> +-- dnode@1.2.2  extraneous
> +-- domready@1.0.8  extraneous
> +-- ecstatic@1.4.0  extraneous
> +-- ejs@2.4.1  extraneous
> +-- glob@7.0.3  extraneous
> +-- requestify@0.1.17
> +-- shoe@0.0.15  extraneous
> +-- socket.io@1.4.5  extraneous
> +-- soundmanager2@2.97.20150601-a  extraneous
> `-- vk-api@0.1.0
> 
> npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Binom\GoogleDrv\Projects\nodejs\MusicBox\node_modules\login\package.json'
> npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Binom\GoogleDrv\Projects\nodejs\MusicBox\node_modules\vc\package.json'
> npm WARN nodejs@1.0.0 No repository field.
> 
> C:\Users\Binom\GoogleDrv\Projects\nodejs\MusicBox>python
> Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> >>> exit()

**Comment by Binom777** [comment]
To install needed
- python
- Node-hy
- Microsoft Visual Studio C ++ 2013 (Express version works well)

Sorry, but this is crazy

**Comment by hgwood** [comment]
This has nothing to do with dnode in particular. You will encounter this problem every time you install something that depends on a native module on Windows. See https://github.com/nodejs/node-gyp/issues/629. Hopefully you can setup you environment properly using the instructions there and never have to worry about it again :). Visual Studio should not be required.
