### ISSUE TITLE
Method Uint8Array.length called on incompatible receiver [object Object]

### ISSUE THREAD

**Issue by yinzishao** [substack/dnode#187]
i want my client can get a mongoose object like [this] (http://stackoverflow.com/questions/39620101/mongoose-typeerror-method-uint8array-length-called-on-incompatible-receiver
)

but i get an error:

Trace: { message: 'Method Uint8Array.length called on incompatible receiver [object Object]' }
    at remote.searches.getSearchResults.reject (/home/youmi/project/aso-rpc/test/client.js:106:21)
    at Proto.apply (/home/youmi/project/aso-rpc/node_modules/dnode-protocol/index.js:123:13)
    at Proto.handle (/home/youmi/project/aso-rpc/node_modules/dnode-protocol/index.js:99:19)
    at D.dnode.handle (/home/youmi/project/aso-rpc/node_modules/dnode/lib/dnode.js:140:21)
    at D.dnode.write (/home/youmi/project/aso-rpc/node_modules/dnode/lib/dnode.js:128:22)
    at Stream.ondata (stream.js:31:26)
    at emitOne (events.js:77:13)
    at Stream.emit (events.js:169:7)
    at Stream.<anonymous> (/home/youmi/project/aso-rpc/node_modules/mux-demux/inject.js:61:14)
    at emitOne (events.js:77:13)

people say the error you get is related to traverse not being able to handle ObjectId instances in your results array

But , my colleague don't have the same issue that means they can traverse ObjectId instances to the client.

i suspect this question is the result of the different version of modules or something?i have no idea to this question~~
my node version is 4.4.7

**Comment by yinzishao** [comment]
I had find the answer of this question.
this is perhaps beacause  of version of the modules mongodb in **monogoose**
i uninstall mongodb in **monogoose**, and install the older version of mongodb driver(2.1.16). it work  !
