### ISSUE TITLE
Doesn't work with Node 12

### ISSUE THREAD

**Issue by Pandorym** [substack/dnode#193]
The problem is that `weak` doesn't work with Node 12 (TooTallNate/node-weak#99).

And we can replace with `weak` with `weak-napi` (TooTallNate/node-weak#97).

Then, it will work.

```
/Users/pandorym/Project/*/node_modules/bindings/bindings.js:88
        throw e
        ^

Error: The module '/Users/pandorym/Project/*/node_modules/weak/build/Release/weakref.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:815:18)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at bindings (/Users/pandorym/Dropbox/Project/PopularizeLaw/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/Users/pandorym/Dropbox/Project/PopularizeLaw/node_modules/weak/lib/weak.js:7:35)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
```

**Comment by RezaErfani67** [comment]
weak-napi also not work for me on win 10

**Comment by dafanzhi** [comment]
i got the same error, then i try to re install dnode, the rebuild error of weak module turns out:
my node version: 12.13.1
```
weak@1.0.1 install /Users/yingzhu/repo/enhancer/payment-center/node_modules/weak
node-gyp rebuild

  CXX(target) Release/obj.target/weakref/src/weakref.o
../src/weakref.cc:147:25: error: too few arguments to function call, expected 4, have 3; did you mean 'Nan::Call'?
  globalCallbackDirect->Call(Nan::GetCurrentContext()->Global(), 1, argv);
                        ^~~~
                        Nan::Call
../../nan/nan_maybe_43_inl.h:345:30: note: 'Nan::Call' declared here
inline MaybeLocal<v8::Value> Call(
                             ^
../src/weakref.cc:168:75: error: too few arguments to function call, single argument 'context' was not specified
  Local<Object> proxy = Nan::New<ObjectTemplate>(proxyClass)->NewInstance();
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/yingzhu/Library/Caches/node-gyp/12.13.1/include/node/v8.h:6292:3: note: 'NewInstance' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(Local<Context> context);
  ^
/Users/yingzhu/Library/Caches/node-gyp/12.13.1/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/weakref.cc:223:55: error: no member named 'IsNearDeath' in 'Nan::Persistent<v8::Object,
      v8::NonCopyablePersistentTraits<v8::Object> >'
  Local<Boolean> rtn = Nan::New<Boolean>(cont->target.IsNearDeath());
                                         ~~~~~~~~~~~~ ^
3 errors generated.
make: *** [Release/obj.target/weakref/src/weakref.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/yingzhu/repo/enhancer/payment-center/node_modules/weak
gyp ERR! node -v v12.13.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: weak@1.0.1 (node_modules/weak):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: weak@1.0.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ dnode@1.2.2
updated 1 package and audited 629 packages in 6.999s
found 0 vulnerabilities

```

**Comment by purejs** [comment]
Strongly hope this issue can be fixed! we have many apps build on dnode, and we can not upgrade nodejs from 10 to current anymore if not fix this issue. please help to make it fixed, thanks very very much!
